package giaodien;

import java.awt.Color;
import java.text.DecimalFormat;
import java.text.ParseException;;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.danhSachNhanVien;
import model.nhanVien;
import test.kiemTra;
import thread.clockTime;

public class quanLyNhanVien extends javax.swing.JFrame {
    // Lấy mô hình dữ liệu của bảng
    private DefaultTableModel tblModel = new DefaultTableModel();
    
    private danhSachNhanVien dsNhanVien = new danhSachNhanVien();
    private boolean editNhanVien = false;

    /**
     Creates new form quanLyNhanVien
     */
    public quanLyNhanVien() {
        //Đặt tên CT
        setTitle("Quản Lý Nhân Viên");
        
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        
        // Hiện đồng hồ
        initClock();
    }
    
    private void initClock() {
        clockTime clock = new clockTime(lblClock);
        clock.start();
    }

    public void initTable() {
        tblModel.setColumnIdentifiers(new Object[]{
            "MÃ", "HỌ VÀ TÊN", "NGÀY SINH", "TUỔI", "EMAIL", "LƯƠNG"
        });
        tblNhanVien.setModel(tblModel);
    }

    /**
     This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnFrist = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnCollectionId = new javax.swing.JButton();
        btnCollectionSalary = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        lblAdmin = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("MÃ NHÂN VIÊN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("HỌ VÀ TÊN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("TUỔI");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("EMAIL");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("LƯƠNG");

        lblClock.setBackground(new java.awt.Color(255, 255, 255));
        lblClock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClock.setForeground(new java.awt.Color(0, 0, 255));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/o'clock.png"))); // NOI18N
        lblClock.setText("0:0:0 AM");
        lblClock.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(255, 153, 0)));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtID.setForeground(java.awt.Color.orange);
        txtID.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIDCaretUpdate(evt);
            }
        });

        txtName.setForeground(java.awt.Color.darkGray);
        txtName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNameCaretUpdate(evt);
            }
        });

        txtEmail.setForeground(java.awt.Color.darkGray);
        txtEmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtEmailCaretUpdate(evt);
            }
        });

        txtSalary.setForeground(java.awt.Color.darkGray);
        txtSalary.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSalaryCaretUpdate(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

        btnNew.setBackground(new java.awt.Color(255, 255, 255));
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 0, 0));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setBackground(new java.awt.Color(255, 255, 255));
        btnFind.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFind.setForeground(new java.awt.Color(255, 0, 0));
        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnFind.setText("Tìm kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnOpen.setBackground(new java.awt.Color(255, 255, 255));
        btnOpen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOpen.setForeground(new java.awt.Color(255, 0, 0));
        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Open file.png"))); // NOI18N
        btnOpen.setText("Mở ");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFind, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFrist.setBackground(new java.awt.Color(255, 255, 255));
        btnFrist.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFrist.setForeground(new java.awt.Color(255, 255, 255));
        btnFrist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/First.png"))); // NOI18N
        btnFrist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFristActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(255, 255, 255));
        btnLast.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Last.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Next.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(255, 255, 255));
        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Prev.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        lblStatus.setForeground(new java.awt.Color(255, 0, 0));
        lblStatus.setText("Bản ghi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFrist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFrist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtAge.setEditable(false);
        txtAge.setForeground(java.awt.Color.darkGray);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        btnCollectionId.setBackground(new java.awt.Color(0, 153, 0));
        btnCollectionId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCollectionId.setForeground(new java.awt.Color(255, 255, 255));
        btnCollectionId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ten.png"))); // NOI18N
        btnCollectionId.setText("Sắp xếp theo mã");
        btnCollectionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectionIdActionPerformed(evt);
            }
        });

        btnCollectionSalary.setBackground(new java.awt.Color(0, 153, 0));
        btnCollectionSalary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCollectionSalary.setForeground(new java.awt.Color(255, 255, 255));
        btnCollectionSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/so.png"))); // NOI18N
        btnCollectionSalary.setText("Sắp xếp theo lương");
        btnCollectionSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollectionSalaryActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(0, 153, 204));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        lblAdmin.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(0, 153, 0));
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setText("Xin chào admin");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("NGÀY SINH");

        txtBirthday.setForeground(java.awt.Color.darkGray);
        txtBirthday.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBirthdayCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCollectionId)
                        .addGap(18, 18, 18)
                        .addComponent(btnCollectionSalary)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(jLabel2))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(txtBirthday))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdmin)
                                    .addComponent(btnDangXuat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCollectionId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCollectionSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtID.setText("");
        txtName.setText("");
        txtBirthday.setText("");
        txtAge.setText("");
        txtEmail.setText("");
        txtSalary.setText("");
        // Sửa nhân viên = false
        editNhanVien = false;
        // backgroud màu trắng
        kiemTra.Start(txtID, txtName,txtBirthday, txtAge, txtEmail, txtSalary);
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            StringBuilder sb = new StringBuilder();
           
            kiemTra.checkEmpty(txtID, sb, "Bạn chưa nhập mã nhân viên.\n");
            kiemTra.checkEmpty(txtName, sb, "Bạn chưa nhập tên nhân viên. \n");
            kiemTra.checkDate(txtBirthday, sb);
            kiemTra.checkAge(txtAge, sb);
            kiemTra.checkEmail(txtEmail, sb);
            kiemTra.checkSalary(txtSalary, sb);
            
            if(sb.length() > 0){
                JOptionPane.showMessageDialog(this, sb.toString(), "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            nhanVien nv = new nhanVien();
            nv.setId(txtID.getText());
            nv.setName(txtName.getText());
            nv.setBirthday(txtBirthday.getText());
            nv.setAge(Integer.parseInt(txtAge.getText()));
            nv.setEmail(txtEmail.getText());
        // chuyển đổi theo đúng định dạng 100.000 để không bị bắt lỗi là kiểu String
            String luong = txtSalary.getText().replaceAll("\\.", "");
            nv.setSalary(Double.parseDouble(luong));

            int mess = 0;
            if (editNhanVien) {// Sửa đổi nhân viên 
                if (dsNhanVien.findById(nv.getId()) == null) {
                    JOptionPane.showMessageDialog(this, "Nhân viên không tồn tại");
                    return;
                } else {
                    dsNhanVien.update(nv);
                    mess = 1;
                }

            } else { // Thêm mới
                if (dsNhanVien.findById(nv.getId()) != null) {
                    JOptionPane.showMessageDialog(this, "Nhân viên đã tồn tại, không thể thêm mới");
                    return;
                } else {
                    dsNhanVien.addNV(nv);
                    mess = 0;
                    // cập nhật lại Status
                    lblStatus.setText(dsNhanVien.getStatus());
                }

            }
            if (mess == 1) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Lưu thành công");
            }

            btnNewActionPerformed(evt);// Xóa trắng
            dsNhanVien.showTable(tblModel);//Hiển thị lên bảng

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String del = JOptionPane.showInputDialog(this,
                "Nhập Mã Nhân viên cần xóa", "Yêu cầu", JOptionPane.OK_CANCEL_OPTION);
            
            if(del != null){
                nhanVien nv = dsNhanVien.findById(del);
                if(nv != null){
                    int chon = (JOptionPane.showConfirmDialog(this, 
                    "Bạn muốn xóa Nhân viên có mã: "+del, "Cảnh báo", JOptionPane.YES_NO_OPTION));
                    
                    if(chon ==  JOptionPane.YES_OPTION){
                        dsNhanVien.deleteById(del);
                    // cập nhật lại Status
                        lblStatus.setText(dsNhanVien.getStatus());
                        btnNewActionPerformed(evt);// Xóa trắng
                        dsNhanVien.showTable(tblModel);// Hiển thị lại bảng
                        JOptionPane.showMessageDialog(this, "Nhân viên đã được xóa");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Nhân viên không tồn tại");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Hủy xóa");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            String find = JOptionPane.showInputDialog(this,
                "Nhập ID Nhân viên cần tìm", "Yêu cầu", JOptionPane.YES_NO_CANCEL_OPTION);
            
            if(find != null){
                nhanVien nv = dsNhanVien.findById(find);
                if(nv != null){
//                    int chon = (JOptionPane.showConfirmDialog(this, 
//                    "Bạn muốn tìm Nhân viên có mã: "+find, "Thông báo", JOptionPane.YES_NO_OPTION));
//                    if(chon ==  JOptionPane.YES_OPTION){
                        hienLenFrom(nv);
                        JOptionPane.showMessageDialog(this, "Tìm nhân viên thành công");
                        
                        // Cập nhật lại Status tại vị trí index 
                        dsNhanVien.viTriIndex(nv);
                        lblStatus.setText(dsNhanVien.getStatus());
                        // Chọn nhân viên hiện tại đc tìm trên bảng
                        tblNhanVien.setRowSelectionInterval(dsNhanVien.viTriIndex(nv), dsNhanVien.viTriIndex(nv));
                     
                }else{
                        JOptionPane.showMessageDialog(this, "Nhân viên không tồn tại");
                    }
            }else{
                JOptionPane.showMessageDialog(this, "Hủy tìm kiếm"); 
                       
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        try {
            // chọn file
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.showOpenDialog(this);
                 // mở file
                dsNhanVien.openFile();
                dsNhanVien.showTable(tblModel); // hiển thị dữ liệu trên bảng
                // Sắp xếp theo ID
                btnCollectionIdActionPerformed(null);
                //Hiển thị nhân viên đầu tiên trên Form
                btnFristActionPerformed(null);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: "+e.getMessage());
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        try {
            int save = (JOptionPane.showConfirmDialog(this, 
                    "Bạn muốn lưu file ?", "Thông báo", JOptionPane.YES_NO_OPTION));
                if(save ==  JOptionPane.YES_OPTION){
        
//                    JFileChooser fileChooser = new JFileChooser();
//                    fileChooser.showSaveDialog(this);
                    dsNhanVien.saveFile();
                    JOptionPane.showMessageDialog(this, "Lưu file thành công");
                    
                }
            int exit = (JOptionPane.showConfirmDialog(this, 
                    "Bạn muốn thoát chương trình ?", "Thông báo", JOptionPane.YES_NO_OPTION));
                if(exit == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: "+e.getMessage());
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void hienLenFrom(nhanVien nv) {
        // chuyển đổi lương ra hệ cơ số Decimal
        DecimalFormat df = dsNhanVien.setCurrency();
        
        editNhanVien = true;
        txtID.setText(nv.getId());
        txtName.setText(nv.getName());
        txtBirthday.setText(nv.getBirthday());
        txtAge.setText("" + nv.getAge());
        txtEmail.setText(nv.getEmail());
        txtSalary.setText(df.format(nv.getSalary()));
    }
    
    private void btnFristActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFristActionPerformed
        dsNhanVien.first();
        lblStatus.setText(dsNhanVien.getStatus());
        nhanVien nv = dsNhanVien.viTriNhanVien();
        hienLenFrom(nv);
        
    //Chọn hàng table theo vị trí index ở trên status
        tblNhanVien.setRowSelectionInterval(dsNhanVien.viTriIndex(nv), dsNhanVien.viTriIndex(nv));
    }//GEN-LAST:event_btnFristActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        dsNhanVien.prev();
        lblStatus.setText(dsNhanVien.getStatus());
        nhanVien nv = dsNhanVien.viTriNhanVien();
        hienLenFrom(nv);
        tblNhanVien.setRowSelectionInterval(dsNhanVien.viTriIndex(nv), dsNhanVien.viTriIndex(nv));
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        dsNhanVien.next();
        lblStatus.setText(dsNhanVien.getStatus());
        nhanVien nv = dsNhanVien.viTriNhanVien();
        hienLenFrom(nv);       
        tblNhanVien.setRowSelectionInterval(dsNhanVien.viTriIndex(nv), dsNhanVien.viTriIndex(nv));
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        dsNhanVien.last();
        lblStatus.setText(dsNhanVien.getStatus());
        nhanVien nv = dsNhanVien.viTriNhanVien();
        hienLenFrom(nv);
        tblNhanVien.setRowSelectionInterval(dsNhanVien.viTriIndex(nv), dsNhanVien.viTriIndex(nv));
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int row = tblNhanVien.getSelectedRow();
        
        if (row >= 0) {
            String id = (String) tblNhanVien.getValueAt(row, 0);
            nhanVien nv = dsNhanVien.findById(id);
            if (nv != null) {
                hienLenFrom(nv);
                dsNhanVien.viTriIndex(nv);
                lblStatus.setText(dsNhanVien.getStatus());
            }
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnCollectionSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectionSalaryActionPerformed
        dsNhanVien.collectionSalary();
        dsNhanVien.showTable(tblModel);
        btnFristActionPerformed(null);
    }//GEN-LAST:event_btnCollectionSalaryActionPerformed

    private void btnCollectionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollectionIdActionPerformed
        dsNhanVien.collectionID();
        dsNhanVien.showTable(tblModel);
        btnFristActionPerformed(null);
    }//GEN-LAST:event_btnCollectionIdActionPerformed

    private void txtNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNameCaretUpdate
        // Có điền dữ liệu vào thì màu trắng
        if(txtName.getText().length() > 0)
            txtName.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtNameCaretUpdate

    private void txtIDCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIDCaretUpdate
        if(txtID.getText().length() > 0)
            txtID.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtIDCaretUpdate

    private void txtEmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtEmailCaretUpdate
        if(txtEmail.getText().length() > 0)
            txtEmail.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtEmailCaretUpdate

    private void txtSalaryCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSalaryCaretUpdate
        if(txtSalary.getText().length() > 0)
            txtSalary.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtSalaryCaretUpdate

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        Login login = new Login();
        // Chạy Login
        login.setVisible(true);
        
        //Dừng quản lý nhân viên
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed
    // Tự động tính tuổi khi nhập ngày sinh
    private void txtBirthdayCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBirthdayCaretUpdate
        if(txtBirthday.getText().length() > 0){
            txtBirthday.setBackground(Color.white);
            txtAge.setBackground(Color.white);
        }
        try {
            int tuoi = dsNhanVien.tinhTuoi(txtBirthday);
            if(txtBirthday.getText().length() > 0)
                txtAge.setText(""+tuoi);
            
        } catch (ParseException e) {
        }
    }//GEN-LAST:event_txtBirthdayCaretUpdate

    /**
     @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollectionId;
    private javax.swing.JButton btnCollectionSalary;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFrist;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables

}
